= Relajet Buildroot SDK

Environment Setup

[source,console]
% sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
 build-essential chrpath  socat bc liblz4-tool \
 libsdl1.2-dev xterm  sed cvs subversion coreutils texi2html \
 docbook-utils python-pysqlite2 help2man make gcc g++ desktop-file-utils \
 libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake groff curl lzop asciidoc

For Ubuntu 12.04 host setup only:
[source,console]
% sudo apt-get install uboot-mkimage

For Ubuntu 14.04 or later revision host setup:
[source,console]
% sudo apt-get install u-boot-tools



To get the SDK you need to have repo installed and use it as:

Download the SDK source:

[source,console]
% git clone https://github.com/RelaJet/buildroot.git
% cd buildroot
% git checkout relajet_201802_1.0.0_ga-wip


To generate the configuration (ex: C Series)
[source,console]
% make relajet_c8328_defconfig
% make -j<N> (N is up to cors number on your host PC)

To generate the configuration (ex: PICO Series)
[source,console]
% make relajet_cpico_defconfig
% make -j<N> (N is up to cors number on your host PC)

To configure the application by your project
[source,console]
% make menuconfig

Output image files for PICO Series:
[source,console]
%SPL
%u-boot.img
%zImage
%uEnv.txt
%imx7d-pico_pi.dtb
%sdcard.img

Output Path: <buildroot path>/output/images/

flashcard the card (ex: PICO Series):
[source,console]
% sudo dd if=sdcard.img of=/dev/sdx bs=1M
NOTE: sdx is your device node

